### ISSUE TITLE
update workflow to build on push

### ISSUE THREAD

**Issue by raynamharris** [ctb/ribbity#33]
currently, the workflow is only triggered on issues. 

```
on:
  issues:
      types: [opened, edited, deleted, closed, reopened, labeled, unlabeled,  transferred]

```

might be good to add on push as well

```
  push:
     branches:
       - main            
```

**Comment by raynamharris** [comment]
this way, any change to config files with trigger the build, not just edits to issues

**Comment by ctb** [comment]
yep. I was actually thinking that a good default would be:

* build site every 15 minutes if it's changed
* rebuild site every week or so just because

but I don't know how to do the first one :)

I don't expect the config file to change that frequently, tho, so this would mostly be of interest to developers, I suspect :).

**Comment by raynamharris** [comment]
i think you can do something like 

```
on:
  schedule: 
  - cron: "*/15 * * * *" # every 15 minutes. set to whatever interval you like
```

**Comment by raynamharris** [comment]
amanda uses 👇  in https://github.com/nih-cfde/published-documentation/blob/stable/.github/workflows/update_C2M2.yml for instance

```
on:
  schedule:
   - cron:  '0 * * * *'
```

**Comment by ctb** [comment]
right, but doesn't tackle "if changed"  though. want to avoid really regular building of the site with no changes!
